### PR TITLE
Deprecate tap helper

### PR DESCRIPTION
**Pull request by sethkinast**

### CODE REVIEW

**Comment by smfoote** [comment]
Can you add a PR to update dustjs.com?

**Comment by sethkinast** [comment]
Deprecations go on the wiki because they're sort of transient, I'll update that in a sec.

Tap doesn't go away until 1.8, long time in the future probably.

**Comment by sethkinast** [comment]
https://github.com/linkedin/dustjs-helpers/wiki/Deprecated-Features#tap

**Comment by prashn64** [comment]
Thanks for updating the wiki

**Pull request merged**
