### PR TITLE
Bump dependencies of dustjs-linked to 3.0

### PR DESCRIPTION
**Pull request by slreynolds**
Updated the dependencies of dustjs-linkedin to `3.0`.

Fixes issue #148

### CODE REVIEW

**Review by gilly3 — APPROVED** [review]

**Comment by gilly3** [comment]
Not that I have any actual authority in this repo to approve changes, but if we can get this merged and published, it would save me from forking it and publishing to my company's private registry.

**Comment by gilly3** [comment]
@jimmyhchan, you most recently merged a PR in this repo.  Can you please merge this one (and publish to npm) to address security concerns?

@sumeetkakkar, you most recently merged a PR in the dustjs repo.  Any chance you are also authorized to merge this PR?

**Comment by sumeetkakkar** [comment]
cc @grawk

**Comment by opletin** [comment]
@grawk Matt can you accept it pls?

**Comment by mikaello** [comment]
Thanks @grawk 🤩 Would it be any chance to publish v1.8.0 to [npmjs.com](https://www.npmjs.com/package/dustjs-helpers?activeTab=versions)?

**Comment by grawk** [comment]
@mikaello Unfortunately I don't have publish permission for the NPM package:

```
$ npm owner ls dustjs-helpers --registry=https://registry.npmjs.org
rragan <rragan@gmail.com>
jimmyhchan <jimmyhchan@gmail.com>
linkedin <acrabtree@linkedin.com>
sethkinast <seth@sethkinast.com>
```

Let me plumb the depths of my LinkedIn messages to see if I can find the current holder of permissions.

**Pull request merged**
