### PR TITLE
Evaluate truth test bodies inside a @select before resolving the select.

### LINKED ISSUE #134: Feature regression in 1.7.0, logic helpers ignored in select bodies
Given this template:
```
{@select key=selectKey}
    {@eq value=1}One{/eq}
    {@eq value=2}
        Two
        {@eq key=testVal value=5}
            Bug!
        {/eq}
    {/eq}
    {@eq value=3}Three{/eq}
{/select}
```

If `selectKey` is 2 and `testVal` is 5, "Two" is rendered but "Bug!" is not.

Here's a jsfiddle to show this in action.  http://jsfiddle.net/hf67o6un/

### PR DESCRIPTION
**Pull request by sethkinast**
Fixes #134

### CODE REVIEW

**Comment by smfoote** [comment]
Does this fix the nested `@eq` case? Your test case doesn't have any nesting, and it looks like your check is too late. I'm not way familiar with this code, so I'm just trying to sanity check.

**Comment by sethkinast** [comment]
The test code has nesting yeah. The `Correct!` block is nested.

**Comment by smfoote** [comment]
Dang it. Apparently I need indentation to read code. Carry on.

**Comment by sethkinast** [comment]
I think at some point this needs re-architected. There's already another failing edge case-- putting sections inside your select will break the select.

A better solution would be a select registry inside context.global and generating an ID for your select. I'll work on this sometime.

**Comment by sethkinast** [comment]
(Sections inside a select has never worked btw, it's not something new in 1.7 or 1.6)

**Pull request merged**
